Translated the AdafruitStepperMotor.py and StepperTest.py
zugaldia/adafruit-motor-hat pull request #2
Opened 2017-07-14 22:09 UTC by jdestremps

Translated the AdafruitStepperMotor.py and StepperTest.py into both Kotlin and Java classes respectively, and have updated MainActivity to run one test or the other (DC or stepper).  Tested with two stepper motors attached.

2017-08-21 14:25 UTC, zugaldia requested changes

2017-08-21 14:25 UTC, zugaldia commented on AdafruitMotorHat/lib/src/main/java/com/zugaldia/adafruit/motorhat/library/AdafruitStepperMotor.java
> +#!/usr/bin/python
This is looking great - thanks for the contribution. Could you remove this Python code from here before we merge?

2017-08-21 18:55 UTC, jdestremps commented
Sure

> On Aug 21, 2017, at 7:25 AM, Antonio Zugaldia <notifications@github.com> wrote:
> 
> @zugaldia requested changes on this pull request.
> 
> In AdafruitMotorHat/lib/src/main/java/com/zugaldia/adafruit/motorhat/library/AdafruitStepperMotor.java:
> 
> > +                    } catch (InterruptedException e) {
> +                        e.printStackTrace();
> +                    }
> +                }
> +            }
> +        }
> +    }
> +}
> +
> +
> +
> +
> +
> +
> +/*
> +#!/usr/bin/python
> This is looking great - thanks for the contribution. Could you remove this Python code from here before we merge?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-23 20:50 UTC, jdestremps commented on AdafruitMotorHat/lib/src/main/java/com/zugaldia/adafruit/motorhat/library/AdafruitStepperMotor.java
> +#!/usr/bin/python
Ok, done.

2017-09-07 21:09 UTC, zugaldia approved these changes

2017-09-07 21:09 UTC, merged

2017-09-07 21:09 UTC, zugaldia commented
Thank you, @jdestremps, again for the contribution!